### SIGNUP USER
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "fullname": "Lenin M",
  "username": "Leninmurugesan",
  "password": "lenin1801",
  "role": "user"
}

### SIGNUP ADMIN
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "fullname": "Devapasath K",
  "username": "devaprasathdev",
  "password": "Hostin001",
  "role": "admin",
  "adminSecret": "adminsecretkey001"
}

### LOGIN
POST http://localhost:4000/auth/signin
Content-Type: application/json

{
  "username": "devaprasathdev",
  "password": "Hostin001"
}

### login
POST http://localhost:4000/auth/signin
Content-Type: application/json

{
  "username": "Leninmurugesan",
  "password": "lenin1801"
}

### CREATE ITEM (ADMIN)
POST http://localhost:4000/db/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTVmNWYyM2RjM2I3MmJiMDg3YmI2ZDIiLCJyb2xlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImRldmFwcmFzYXRoZGV2IiwiaWF0IjoxNzY3ODU4MDM4LCJleHAiOjE3Njc4NjE2Mzh9.AXhnxd5efSPO3qSYClWi6A7Uttn0WLqbZdKgdF-KdEI
Content-Type: application/json

{
  "id":"item_L001",
  "name":"HP laptop",
  "category":"Electronics",
  "pricePerMonth":5000,
  "deposit":500,
  "description":"A high performance laptop suitable for all your computing needs.",
  "images":["https://th.bing.com/th/id/OIP.LYPINLY-AlXKtxzSSjIUTQHaHa?w=193&h=194&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"],
  "availability":true,
  "city":"Chennai",
  "condition":"new"
}

### GET ITEMS
GET http://localhost:4000/db/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTVmNWYyM2RjM2I3MmJiMDg3YmI2ZDIiLCJyb2xlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImRldmFwcmFzYXRoZGV2IiwiaWF0IjoxNzY5MTU4MzAxLCJleHAiOjE3NjkxNjE5MDF9.2y4a8AfDiv8ChOqtzn7iZ3hpH7vmKjOyJ5szhdlwqBc

### DELETE ITEM BY CUSTOM ID
DELETE http://localhost:4000/db/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTVmNWYyM2RjM2I3MmJiMDg3YmI2ZDIiLCJyb2xlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImRldmFwcmFzYXRoZGV2IiwiaWF0IjoxNzY5MTU0NTE5LCJleHAiOjE3NjkxNTgxMTl9.-vBR7NAvcxG_0tWUoJ7w8zIdxkSSycr8amBLA3nH4Lo

###
PATCH http://localhost:4000/db/item_B001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTVmNWYyM2RjM2I3MmJiMDg3YmI2ZDIiLCJyb2xlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImRldmFwcmFzYXRoZGV2IiwiaWF0IjoxNzY5MTU0NTE5LCJleHAiOjE3NjkxNTgxMTl9.-vBR7NAvcxG_0tWUoJ7w8zIdxkSSycr8amBLA3nH4Lo
Content-Type: application/json

{
"pricePerMonth":100,
"deposit":50
}

### vendor
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "fullname": "Kathirvel K",
  "username": "kathirvelkathir",
  "password": "Boost001",
  "role": "vendors",
  "adminSecret": "adminsecretkey001"
}